spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    placeholders:
      emailCheck: "buyer_email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'"

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

images:
  provider: ${IMAGE_PROVIDER}
  upload-dir: ${IMAGE_UPLOAD_DIR}
  bucket: ${IMAGE_BUCKET}
  base-url: ${IMAGE_BASE_URL}

jwt:
  secret: ${JWT_SECRET}
