spring:
  application:
    name: yell-store-services

  profiles:
    default: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    error:
      include-message: always

  jpa:
    show-sql: false

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail.smtp:
        auth: false
        starttls:
          enable: false

logging:
  level:
    root: INFO
    org:
      # Disables showing database information on startup
      hibernate.orm.connections.pooling: WARN
      # Prevent logger noise on malformed HTTP requests
      apache:
        catalina.connector.CoyoteAdapter: ERROR
        coyote.http11:
          Http11InputBuffer: ERROR
          Http11Processor: ERROR
        tomcat.util.http.parser.HttpParser: ERROR
