spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    placeholders:
      emailCheck: "buyer_email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'"

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

images:
  provider: ${IMAGE_PROVIDER:LOCAL}
  upload-dir: ${IMAGE_UPLOAD_DIR:uploads}
  bucket: ${IMAGE_BUCKET:}
  base-url: ${IMAGE_BASE_URL:}

paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
  mode: sandbox

jwt:
  secret: ${JWT_SECRET:5ffSrvavg96EzEcIf04juxRFgA1vudQ7WUOjbO2LgGk}
