spring:
  application:
    name: yell-store-services

  profiles:
    default: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    org:
      hibernate:
        orm:
          connections:
            # Disables showing database information on startup
            pooling: WARN
