ALTER TABLE orders
    ADD COLUMN order_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE orders
    ADD CONSTRAINT orders_order_number_unique UNIQUE (order_number);

ALTER SEQUENCE orders_order_number_seq RESTART WITH 10482812;
